# Generated by Django 5.2.10 on 2026-01-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_costcenter_alter_systemlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='encrypted_samba_password',
            field=models.BinaryField(blank=True, null=True, verbose_name='Samba Passwort (verschlüsselt)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='samba_username',
            field=models.CharField(default='dmsuser', help_text='Benutzername für Netzwerkfreigaben', max_length=50, verbose_name='Samba Benutzername'),
        ),
    ]
