# Generated by Django 5.2.10 on 2026-01-16 16:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dms', '0003_systemsettings_encrypted_samba_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Aktenzeichen')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('retention_years', models.PositiveIntegerField(default=10, help_text='0 = unbegrenzt', verbose_name='Aufbewahrungsfrist (Jahre)')),
                ('retention_trigger', models.CharField(choices=[('CREATION', 'Ab Erstellung'), ('EXIT', 'Ab Austritt'), ('DOCUMENT_DATE', 'Ab Dokumentdatum')], default='EXIT', max_length=50, verbose_name='Fristbeginn')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Pflichtakte')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dms.filecategory', verbose_name='Übergeordnete Kategorie')),
            ],
            options={
                'verbose_name': 'Aktenkategorie',
                'verbose_name_plural': 'Aktenkategorien (Aktenplan)',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_number', models.CharField(help_text='Eindeutige Aktennummer', max_length=50, unique=True, verbose_name='Aktenzeichen')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('INACTIVE', 'Inaktiv (ausgeschieden)'), ('ARCHIVED', 'Archiviert'), ('DELETED', 'Zur Löschung vorgemerkt')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('opened_at', models.DateField(auto_now_add=True, verbose_name='Eröffnungsdatum')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Schließungsdatum')),
                ('retention_until', models.DateField(blank=True, null=True, verbose_name='Aufbewahren bis')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_file', to='dms.employee', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Personalakte',
                'verbose_name_plural': 'Personalakten',
                'ordering': ['file_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('action', models.CharField(choices=[('CREATE', 'Erstellt'), ('VIEW', 'Angesehen'), ('DOWNLOAD', 'Heruntergeladen'), ('EDIT', 'Bearbeitet'), ('DELETE', 'Gelöscht'), ('ARCHIVE', 'Archiviert'), ('RESTORE', 'Wiederhergestellt'), ('PERMISSION_CHANGE', 'Berechtigung geändert'), ('VERSION_CREATE', 'Version erstellt')], max_length=20, verbose_name='Aktion')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('old_value', models.TextField(blank=True, verbose_name='Alter Wert')),
                ('new_value', models.TextField(blank=True, verbose_name='Neuer Wert')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dms.document', verbose_name='Dokument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('personnel_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dms.personnelfile', verbose_name='Personalakte')),
            ],
            options={
                'verbose_name': 'Audit-Protokoll',
                'verbose_name_plural': 'Audit-Protokolle',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('CATEGORY', 'Kategorie'), ('PERSONNEL_FILE', 'Personalakte'), ('DEPARTMENT', 'Abteilung')], max_length=20, verbose_name='Zieltyp')),
                ('permission_level', models.CharField(choices=[('VIEW', 'Ansehen'), ('EDIT', 'Bearbeiten'), ('DELETE', 'Löschen'), ('ADMIN', 'Vollzugriff')], default='VIEW', max_length=20, verbose_name='Berechtigungsstufe')),
                ('inherit_to_children', models.BooleanField(default=True, verbose_name='Auf Unterordner vererben')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dms.department', verbose_name='Abteilung')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dms_permissions', to='auth.group', verbose_name='Gruppe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dms_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dms.filecategory', verbose_name='Kategorie')),
                ('personnel_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dms.personnelfile', verbose_name='Personalakte')),
            ],
            options={
                'verbose_name': 'Zugriffsberechtigung',
                'verbose_name_plural': 'Zugriffsberechtigungen',
                'ordering': ['target_type', 'permission_level'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='Versionsnummer')),
                ('encrypted_content', models.BinaryField(verbose_name='Verschlüsselter Inhalt')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dateigröße')),
                ('sha256_hash', models.CharField(max_length=64, verbose_name='SHA-256 Hash')),
                ('change_reason', models.CharField(blank=True, max_length=500, verbose_name='Änderungsgrund')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dms.document', verbose_name='Dokument')),
            ],
            options={
                'verbose_name': 'Dokumentenversion',
                'verbose_name_plural': 'Dokumentenversionen',
                'ordering': ['document', '-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='PersonnelFileEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.PositiveIntegerField(verbose_name='Laufende Nr.')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Eintragsdatum')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Dokumentdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_entries', to='dms.filecategory', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_entries', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_entries', to='dms.document', verbose_name='Dokument')),
                ('personnel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_entries', to='dms.personnelfile', verbose_name='Personalakte')),
            ],
            options={
                'verbose_name': 'Akteneintrag',
                'verbose_name_plural': 'Akteneinträge',
                'ordering': ['personnel_file', '-entry_number'],
                'unique_together': {('personnel_file', 'entry_number')},
            },
        ),
    ]
