# Generated by Django 5.2.10 on 2026-01-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_aktenlogik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Sage-Ordnername (z.B. 0000001)', max_length=20, unique=True, verbose_name='Mandanten-Code')),
                ('name', models.CharField(max_length=200, verbose_name='Mandantenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mandant',
                'verbose_name_plural': 'Mandanten',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Mandanten-Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mandanten-Benutzer',
                'verbose_name_plural': 'Mandanten-Benutzer',
            },
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=50, verbose_name='Mitarbeiter-ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sage_cloud_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sage Cloud ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sage_local_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sage Local ID'),
        ),
        migrations.AlterField(
            model_name='filecategory',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Aktenzeichen'),
        ),
        migrations.AlterField(
            model_name='importedleaverequest',
            name='sage_request_id',
            field=models.CharField(max_length=100, verbose_name='Sage Anfrage-ID'),
        ),
        migrations.AlterField(
            model_name='personnelfile',
            name='file_number',
            field=models.CharField(help_text='Eindeutige Aktennummer', max_length=50, verbose_name='Aktenzeichen'),
        ),
        migrations.AlterField(
            model_name='processedfile',
            name='sha256_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='accesspermission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='filecategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_categories', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='importedleaverequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='importedtimesheet',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='personnelfile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_files', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='processedfile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_files', to='dms.tenant'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_costcenter_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_department_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_id'), name='unique_employee_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='processedfile',
            constraint=models.UniqueConstraint(fields=('tenant', 'sha256_hash'), name='unique_processed_file_per_tenant'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dms.tenant'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('user', 'tenant')},
        ),
    ]
