# Generated by Django 5.2.10 on 2026-01-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_add_tenant_multitenancy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_documenttype_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='filecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_filecategory_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='importedleaverequest',
            constraint=models.UniqueConstraint(fields=('tenant', 'sage_request_id'), name='unique_leaverequest_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='personnelfile',
            constraint=models.UniqueConstraint(fields=('tenant', 'file_number'), name='unique_personnelfile_per_tenant'),
        ),
    ]
