# Generated by Django 5.2.10 on 2026-01-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_add_more_tenant_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='sage_local_id',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='encrypted_sage_local_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='sage_local_api_user',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='sage_local_timeout',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='sage_local_wsdl_url',
        ),
    ]
