# Generated by Django 5.2.10 on 2026-01-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_remove_sage_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='document_storage_path',
        ),
    ]
