# Generated by Django 5.2.10 on 2026-01-17 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0009_add_scan_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex-Farbcode (z.B. #3B82F6)', max_length=7, verbose_name='Farbe')),
                ('is_inbox_tag', models.BooleanField(default=False, help_text='Wird automatisch bei neuen Dokumenten gesetzt', verbose_name='Inbox-Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dms.tag', verbose_name='Übergeordneter Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dms.tenant')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Regelname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('priority', models.IntegerField(default=0, help_text='Höhere Werte = höhere Priorität', verbose_name='Priorität')),
                ('algorithm', models.CharField(choices=[('NONE', 'Keine Zuordnung'), ('ANY', 'Beliebiges Wort'), ('ALL', 'Alle Wörter'), ('EXACT', 'Exakte Phrase'), ('REGEX', 'Regulärer Ausdruck'), ('FUZZY', 'Ähnlichkeitssuche')], default='ANY', max_length=20, verbose_name='Algorithmus')),
                ('match_pattern', models.TextField(help_text='Suchbegriffe oder Regex-Pattern', verbose_name='Suchmuster')),
                ('is_case_sensitive', models.BooleanField(default=False, verbose_name='Groß-/Kleinschreibung beachten')),
                ('assign_status', models.CharField(blank=True, max_length=20, verbose_name='Status setzen')),
                ('match_count', models.IntegerField(default=0, verbose_name='Anzahl Treffer')),
                ('last_matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Treffer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.documenttype', verbose_name='Dokumenttyp zuweisen')),
                ('assign_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.employee', verbose_name='Mitarbeiter zuweisen')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='dms.tenant')),
                ('assign_tags', models.ManyToManyField(blank=True, to='dms.tag', verbose_name='Tags zuweisen')),
            ],
            options={
                'verbose_name': 'Matching-Regel',
                'verbose_name_plural': 'Matching-Regeln',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='dms.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_documents', to='dms.tag')),
            ],
            options={
                'verbose_name': 'Dokument-Tag',
                'verbose_name_plural': 'Dokument-Tags',
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tag_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together={('document', 'tag')},
        ),
    ]
