# Generated by Django 5.2.10 on 2026-01-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_add_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='file_category',
            field=models.ForeignKey(blank=True, help_text='Zuordnung zum Aktenplan - Dokumente dieses Typs werden automatisch in diese Unterakte einsortiert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='dms.filecategory', verbose_name='Aktenkategorie'),
        ),
    ]
