# Generated by Django 5.2.10 on 2026-01-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0012_doctype_to_filecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_date',
        ),
        migrations.AddField(
            model_name='document',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Monat der Periode (1-12)', null=True, verbose_name='Periode Monat'),
        ),
        migrations.AddField(
            model_name='document',
            name='period_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Jahr der Periode (z.B. 2025)', null=True, verbose_name='Periode Jahr'),
        ),
    ]
